POST http://localhost:8080/api/users HTTP/1.1
Content-Type: application/json

{
  "email": "test@example.com"
}

###

POST http://localhost:8080/api/users HTTP/1.1
Content-Type: application/json

{
  "email": "cyberis@example.com"
}

###

POST http://localhost:8080/api/users HTTP/1.1
Content-Type: application/json

{
  "email": "mloneusk@example.com"
}

###

POST http://localhost:8080/api/users HTTP/1.1
Content-Type: application/json

{
  "email": "dackjorsey@example.com"
}

###

POST http://localhost:8080/admin/reset HTTP/1.1
Content-Type: application/json